export const Cookies = {
  TravelType: "travel-type",
  TravelMode: "travel-mode",
  TravelCabin: "travel-cabin",
  TravelTraveller: "travel-traveller",
  TravelBaggage: "travel-baggage",
  TravelOrigin: "travel-origin",
  TravelDestination: "travel-destination",
  TravelPeriod: "travel-period",
  RequestAccess: "request-access",
  LastBooking: "last-booking",
  PreferredSignInProvider: "preferred-signin-provider",
  SpendingPeriod: "spending-period",
  ChartType: "chart-type",
  TransactionsPeriod: "transactions-period",
  TransactionsColumns: "transactions-columns",
  MfaSetupVisited: "mfa-setup-visited",
  MenuConfig: "menu-config-v2",
  InboxFilter: "inbox-filter-v2",
  TrackingConsent: "tracking-consent",
  InboxOrder: "inbox-order",
  HideConnectFlow: "hide-connect-flow",
};
