export const Cookies = {
  PreferredSignInProvider: "preferred-signin-provider",
  SpendingPeriod: "spending-period",
  ChartType: "chart-type",
  TravelType: "travel-type",
  TravelPeriod: "travel-period",
  TravelCabin: "travel-cabin",
  TravelPassenger: "travel-passenger",
  TravelLuggage: "travel-luggage",
  TransactionsPeriod: "transactions-period",
  TransactionsColumns: "transactions-columns",
  MfaSetupVisited: "mfa-setup-visited",
  MenuConfig: "menu-config",
  InboxFilter: "inbox-filter-v2",
  TrackingConsent: "tracking-consent",
  InboxOrder: "inbox-order",
  HideConnectFlow: "hide-connect-flow",
  RequestAccess: "request-access",
};
