export const chatExamples = [
  `What's my trip itinerary`,
  `What's the status of my flight`,
  "Show me hotel options near the airport",
  "What is the check-in time for my hotel",
  "Find my travel booking reference",
  "Find my flight number",
  `What's the weather forecast for my destination`,
  `What's the traffic update for my route`,
  "Create a travel expense report",
  "Recommend a restaurant near my hotel",
  "Recommend a local attraction",
  "Find a travel document",
  "Travel alerts for my destination",
  "Top things to do at my destination",
  "Can I change my flight",
  "Can I cancel my hotel booking",
  "What is the baggage policy for my airline",
];
